# Generated by Django 3.2.7 on 2021-09-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210928_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='folder',
            name='topic',
            field=models.ManyToManyField(to='myapp.Topic'),
        ),
    ]
